#
# Copyright (c) 2024 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Reserve space for the PSA-ADAC
CONFIG_PM_PARTITION_SIZE_MCUBOOT=0x20000

# PSA-ADAC configuration
CONFIG_BOOT_ED25519_PSA=y
CONFIG_PSA_WANT_ECC_TWISTED_EDWARDS_255=y
CONFIG_PSA_WANT_KEY_TYPE_ECC_KEY_PAIR_IMPORT=y
CONFIG_PSA_WANT_ALG_SHA_512=y
CONFIG_PSA_WANT_ALG_ED25519PH=y
CONFIG_PSA_WANT_GENERATE_RANDOM=y

# Do not open approtect at startup
CONFIG_NRF_APPROTECT_USER_HANDLING=y
CONFIG_NRF_SECURE_APPROTECT_USER_HANDLING=y
